version: '3'

services:
        web:
                build: .
                command: python manage.py runserver 0.0.0.0:5000
                volumes:
                        - .:/tool
                ports:
                        - "5000:5000"
