# Generated by Django 3.0.4 on 2020-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
